//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_120
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen
    {
        public int citizenID { get; set; }
        public string name { get; set; }
        public string firstName { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> incomePerMonth { get; set; }
        public Nullable<int> fk_buildingID { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
