//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_120
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int BenutzerID { get; set; }
        public string Benutzername { get; set; }
        public string Passwort { get; set; }
        public byte[] Avatar { get; set; }
    }
}
